kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: findit
spec:
  selector:
    matchLabels:
      app: aspnetcore
      role: backend
  replicas: 1
  template:
    metadata:
      name: findit-deployment
      labels:
        app: aspnetcore
        role: backend
        env: develop
    spec:
      containers:
      - name: apsnetcore
        image: gcr.io/gcr-project/sample:1.0.0
        env:
          - name: PORT
            value: "5000"
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          timeoutSeconds: 5
        ports:
        - name: backend-port
          containerPort: 5000