kind: Deployment
apiVersion: apps/v1
metadata:
  name: findit
spec:
  selector:
    matchLabels:
      app: findit
      role: backend
  replicas: 1
  template:
    metadata:
      name: findit-api-deployment
      labels:
        app: findit
        role: backend
        env: develop
    spec:
      containers:
      - name: findit
        image: gcr.io/gcr-project/sample:1.0.0
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: development
          - name: API_PATH
            value: /api
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: findit-port
          containerPort: 80
    
        