apiVersion: apps/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: findit-api-ingress
spec:
  backend:
    serviceName: findit-api-service
    servicePort: 5000
  rules:
  - host: findit-backend.exams.et6nh.gebeya.co
    http:
      paths:
      - backend:
          serviceName: findit-api-service
          servicePort: 5000
        path: /api