apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: findit-api-ingress
spec:
  backend:
    serviceName: findit-api-service
    servicePort: 80
  rules:
  - host: findit-backend.app.et6nh.gebeya.co
    http:
      paths:
      - backend:
          serviceName: findit-api-service
          servicePort: 80
        path: /api
  tls:
  - hosts:
    - findit-backend.app.et6nh.gebeya.co
    secretName: findit-backend-tls