apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: findit-ingress
spec:
  backend:
    serviceName: findit-service
    servicePort: 5000
  rules:
  - host: findit-backend.apps.et6nh.gebeya.co
    http:
      paths:
      - backend:
          serviceName: findit-service
          servicePort: 5000
        path: /