apiVersion: v1
kind: Service
metadata:
  name: findit-api-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: findit
    role: backend
