apiVersion: v1
kind: Service
metadata:
  name: findit-service
  labels: 
    app: aspnetcore
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: aspnetcore
