apiVersion: v1
kind: Service
metadata:
  name: findit-service
  labels: 
    app: aspnetcore
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: aspnetcore
    role: backend
